apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: web
  name: django-app
  labels:
    app: django
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: django
        image: REPLACE_IMAGE  # Replace with your image
        ports:
        - containerPort: 8000
        env:
        - name: DJANGO_SETTINGS_MODULE
          value: "your_project.settings"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: database_url
        - name: DEBUG
          value: "True"  # Set to "False" for production
---
apiVersion: v1
kind: Service
metadata:
  namespace: web
  name: django-service
  labels:
    app: django
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8000
      nodePort: 30081
  selector:
    app: django
  type: NodePort
