# Generated by Django 4.2.2 on 2023-07-15 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="dob",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="image",
            field=models.BinaryField(blank=True),
        ),
        migrations.DeleteModel(
            name="EditProfile",
        ),
    ]
