# Generated by Django 4.2.2 on 2023-06-16 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_community_category_alter_community_membors"),
    ]

    operations = [
        migrations.RenameField(
            model_name="community",
            old_name="admin",
            new_name="creator",
        ),
    ]
