# Generated by Django 4.2.2 on 2023-06-26 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_post"),
    ]

    operations = [
        migrations.CreateModel(
            name="EditProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recoveryEmail", models.EmailField(max_length=255)),
                ("image", models.BinaryField(blank=True)),
                ("dob", models.DateField()),
                ("bio", models.TextField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
